### ISSUE TITLE
Gradebook archive fails

### ISSUE THREAD

**Issue by steveswinsburg** [steveswinsburg/sakai-archiver#119]
```
Archiving sakai.gradebook.tool with provider org.sakaiproject.archiver.provider.GradebookArchiver (2017-08-25 15:41:04,118 pool-8-thread-1_org.sakaiproject.archiver.impl.ArchiverServiceImpl)
ERROR: An exception occurred whilst archiving content for site chem113_s15 and tool sakai.gradebook.tool. The archive may be incomplete. (2017-08-25 15:41:04,309 pool-8-thread-1_org.sakaiproject.archiver.impl.ArchiverServiceImpl)
java.lang.IllegalArgumentException: Cannot format given Object as a Number
        at java.text.DecimalFormat.format(DecimalFormat.java:507)
        at java.text.Format.format(Format.java:157)
        at org.sakaiproject.archiver.provider.util.FormatHelper.formatDoubleToDecimal(FormatHelper.java:32)
        at org.sakaiproject.archiver.provider.GradebookArchiver.buildRow(GradebookArchiver.java:196)
        at org.sakaiproject.archiver.provider.GradebookArchiver.lambda$archive$0(GradebookArchiver.java:110)
        at java.util.ArrayList.forEach(ArrayList.java:1249)
        at org.sakaiproject.archiver.provider.GradebookArchiver.archive(GradebookArchiver.java:109)
        at org.sakaiproject.archiver.impl.ArchiverServiceImpl.lambda$startArchive$1(ArchiverServiceImpl.java:141)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by steveswinsburg** [comment]
I cant reproduce this so have requested a gradebook export to load the data in. I tried letter grade mode in the gradebook and that didn't break it in this way either.

**Comment by steveswinsburg** [comment]
NumberFormat throws this exception if the input is null. I think the behaviour in Sakai 10 was to return null for grades that are missing so this causes the exception. Can't reproduce in Sakai 12 but have added a null guard in the FormatHelper.
