### ISSUE TITLE
Tests & Quizzes - Gradebook Error

### ISSUE THREAD

**Issue by cacostantino** [steveswinsburg/sakai-archiver#50]
We know you haven't done the Tests & Quizzes work yet, but we wanted to add content and got this message...
![t q](https://cloud.githubusercontent.com/assets/29150601/26738454/2b6e3352-479c-11e7-9896-44f239bdc2d3.jpeg)

**Comment by steveswinsburg** [comment]
Hi @cacostantino, can you please try again? I just logged in to check on this and didn't get the error. I think because it was a new site the gradebook provisioning hadn't been completed yet. Seems to be now. Cheers.

**Comment by cacostantino** [comment]
Hi @steveswinsburg, I just tried to create a new test and got the same error again. Using the "Create using assessment builder" > Create option.

**Comment by steveswinsburg** [comment]
Ok what site are you in and what user are you using?

sent from my mobile

**Comment by steveswinsburg** [comment]
Ah I see it now. Ok that's weird. I'll investigate it.

**Comment by steveswinsburg** [comment]
Ok this is a bug in Sakai. I'm getting this stacktrace:

```
06-Jun-2017 11:03:59.500 WARN [http-nio-8080-exec-10] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions SQL Error: 1210, SQLState: HY000
06-Jun-2017 11:03:59.501 ERROR [http-nio-8080-exec-10] org.hibernate.engine.jdbc.spi.SqlExceptionHelper.logExceptions (conn:6128) Incorrect arguments to mysqld_stmt_execute
Query is: insert into SAM_SECTION_T (ASSESSMENTID, DURATION, SEQUENCE, TITLE, DESCRIPTION, TYPEID, STATUS, CREATEDBY, CREATEDDATE, LASTMODIFIEDBY, LASTMODIFIEDDATE) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?), parameters [14,<null>,1,'Default',<Buffer:''>,21,1,'admin','2017-06-06 11:03:59.492','admin','2017-06-06 11:03:59.492']
06-Jun-2017 11:03:59.501 WARN [http-nio-8080-exec-10] org.sakaiproject.tool.assessment.facade.AssessmentFacadeQueries.createAssessment problem saving assessment: JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1210]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
06-Jun-2017 11:03:59.501 WARN [http-nio-8080-exec-10] org.sakaiproject.tool.assessment.services.PersistenceHelper.retryDeadlock Error saving to db...retry again....
06-Jun-2017 11:03:59.501 WARN [http-nio-8080-exec-10] org.sakaiproject.tool.assessment.services.PersistenceHelper.retryDeadlock JDBC exception on Hibernate data access: SQLException for SQL [n/a]; SQL state [HY000]; error code [1210]; could not execute statement; nested exception is org.hibernate.exception.GenericJDBCException: could not execute statement
06-Jun-2017 11:03:59.503 ERROR [http-nio-8080-exec-10] org.sakaiproject.tool.assessment.services.assessment.AssessmentService.createAssessment 
java.lang.NullPointerException
	at org.sakaiproject.tool.assessment.osid.shared.impl.IdImpl.<init>(IdImpl.java:34)
	at org.sakaiproject.tool.assessment.facade.SectionFacadeQueries.getId(SectionFacadeQueries.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by steveswinsburg** [comment]
I've posted on the sakai dev list to see what's up. I may need to take the server down at some stage to adjust it.

**Comment by steveswinsburg** [comment]
Ok this is to do with the database driver. I'll see if I can correct this.

**Comment by steveswinsburg** [comment]
Hi @cacostantino this should be fixed on the latest build. I have replaced the database driver. let me know if you have any more issues related to this. Cheers.
